apiVersion: 1
datasources:
  - name: QuestDB
    type: questdb-questdb-datasource
    uid: QuestDB
    access: proxy
    isDefault: true
    jsonData:
      server: questdb
      port: 8812
      username: admin
      tlsMode: disable
    secureJsonData:
      password: quest
